name: Run Tests

on:
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install Just
      uses: extractions/setup-just@v2

    - name: Install dependencies
      run: just install

    - name: Build project
      run: just build

    - name: Run integration tests
      env:
        SEED: "//Alice"
        PORT: 3000
        NODE_ENV: test
      run: just test-integration

    - name: Start server in background
      env:
        SEED: "//Alice"
        PORT: 3000
        NODE_ENV: test
      run: |
        node dist/main.js > server.log 2>&1 &
        echo $! > server.pid
        
        # Wait for server to be ready
        for i in {1..15}; do
          if curl -f -s http://localhost:3000/api/health > /dev/null 2>&1; then
            echo "✅ Server is ready!"
            exit 0
          fi
          sleep 2
        done
        
        echo "❌ Server failed to start"
        cat server.log
        exit 1
    - name: Run e2e tests
      env:
        SEED: "//Alice"
        PORT: 3000
        NODE_ENV: test
        CI: true
      run: just test-e2e

    - name: Stop server
      run: |
        if [ -f server.pid ]; then
          kill $(cat server.pid) || true
        fi 
